---
title: "Biostat 203B Homework 1"
subtitle: Due Jan 23, 2026 @ 11:59PM
author: Rebekah Patel and 605566820
format:
  html:
    theme: cosmo
    embed-resources: true
    number-sections: false
    toc: true
    toc-depth: 4
    toc-location: left
    code-fold: false
    link-external-icon: true
    link-external-newwindow: true
---

Display machine information for reproducibility:
```{r}
#| eval: true
sessionInfo()
```

## Q1. Git/GitHub

**No handwritten homework reports are accepted for this course.** We work with Git and GitHub. Efficient and abundant use of Git, e.g., frequent and well-documented commits, is an important criterion for grading your homework.

1. Apply for the [Student Developer Pack](https://education.github.com/pack) at GitHub using your UCLA email. You'll get GitHub Pro account for free (unlimited public and private repositories).

2. Create a **private** repository `biostat-203b-2026-winter` and add `Hua-Zhou` and TA team (`BowenZhang2001` for Lec 1; `Tomoki-Okuno` and `yucais` for Lec 82) as your collaborators with write permission.

3. Top directories of the repository should be `hw1`, `hw2`, ... Maintain two branches `main` and `develop`. The `develop` branch will be your main playground, the place where you develop solution (code) to homework problems and write up report. The `main` branch will be your presentation area. Submit your homework files (Quarto file `qmd`, `html` file converted by Quarto, all code and extra data sets to reproduce results) in the `main` branch.

4. After each homework due date, course reader and instructor will check out your `main` branch for grading. Tag each of your homework submissions with tag names `hw1`, `hw2`, ... Tagging time will be used as your submission time. That means if you tag your `hw1` submission after deadline, penalty points will be deducted for late submission.

5. After this course, you can make this repository public and use it to demonstrate your skill sets on job market.

**Solution:** I have followed the instructions and created the private repository `biostat-203b-2026-winter` on GitHub. I have added `Hua-Zhou` and the TA team as collaborators with write permission. The top directory of the repository is `hw1`. I have maintained two branches, `main` and `develop`, as specified. I will ensure to submit my homework files in the `main` branch and tag each submission appropriately after the due date.

## Q2. Data ethics training

This exercise (and later in this course) uses the [MIMIC-IV data v3.1](https://physionet.org/content/mimiciv/3.1/), a freely accessible critical care database developed by the MIT Lab for Computational Physiology. Follow the instructions at <https://mimic.mit.edu/docs/gettingstarted/> to (1) complete the CITI `Data or Specimens Only Research` course and (2) obtain the PhysioNet credential for using the MIMIC-IV data. Display the verification links to your completion report and completion certificate here. **You must complete Q2 before working on the remaining questions.** (Hint: The CITI training takes a few hours and the PhysioNet credentialing takes a couple days; do not leave it to the last minute.)

**Solution:** I have completed the CITI `Data or Specimens Only Research` course and obtained the PhysioNet credential for using the MIMIC-IV data. Here are the verification links to my completion report and completion certificate:
- [CITI Completion Report](https://www.citiprogram.org/verify/?k318cdeb0-be2d-4fdc-920c-e9b61a5cfcce-74519017)
- [CITI Completion Certificate](https://www.citiprogram.org/verify/?w4805c31f-9c37-4302-8bdf-06ab3a70185c-74519017)

## Q3. Linux Shell Commands

1. Make the MIMIC-IV v3.1 data available at location `~/mimic`. The output of the `ls -l ~/mimic` command should be similar to the below (from my laptop).
```{bash}
#| eval: true
# ln -s /Users/rebekahpatel/BIOSTAT203B/mimic-iv-3.1 ~/mimic
# content of mimic folder
ls -l ~/mimic/
```
Refer to the documentation <https://physionet.org/content/mimiciv/3.1/> for details of data files. Do **not** put these data files into Git; they are big. Do **not** copy them into your directory. Do **not** decompress the gz data files. These create unnecessary big files and are not big-data-friendly practices. Read from the data folder `~/mimic` directly in following exercises. 

  Use Bash commands to answer following questions.

2. Display the contents in the folders `hosp` and `icu` using Bash command `ls -l`. Why are these data files distributed as `.csv.gz` files instead of `.csv` (comma separated values) files? Read the page <https://mimic.mit.edu/docs/iv/> to understand what's in each folder.

```{bash}
ls -l ~/mimic/hosp

ls -l ~/mimic/icu
```
**Solution:** The data files are distributed as `.csv.gz` files instead of `.csv` files to save storage space and reduce download times. Compressed files take up less disk space and can be transferred more quickly over the internet. This is particularly important for large datasets like MIMIC-IV, which can be several gigabytes in size. By using gzip compression, users can efficiently download and store the data without needing excessive storage capacity.

3. Briefly describe what Bash commands `zcat`, `zless`, `zmore`, and `zgrep` do.

**Solution:** 
- zcat: This command uncompresses a list of files like .gz or its standard input and writes the uncompressed data on standard ouput.
- zless: This command allows examination of compressed or plain text files one screenful on a terminal. If the files are compressed, the command uncompresses them itself.
- zmore: This command also allows examination of compressed files and uncompresses them itself, one screenful at a time.
- zgrep: This command searches expressions in compressed files, without needing to decompress them first.

4. (Looping in Bash) What's the output of the following bash script?
```{bash}
#| eval: false
for datafile in ~/mimic/hosp/{a,l,pa}*.gz
do
  ls -l $datafile
done
```
**Solution:** The output of the following bash script is the list of the compressed files in hosp directory that start with a, l, or pa and their details such as file size, permissions, owner, group, and modification date.

Display the number of lines in each data file using a similar loop. (Hint: combine linux commands `zcat <` and `wc -l`.)

```{bash}
for datafile in ~/mimic/hosp/{a,l,pa}*.gz
do
  echo $datafile; zcat < $datafile | wc -l
done
```

**Solution:** The following bash script loops through the hosp directory, finds the zipped files starting with a, l, or pa, prints their path name, unzips them using zcat, and counts the number of lines in each file using wc -l. The output will the be number of lines in each file.

5. Display the first few lines of `admissions.csv.gz`. How many rows are in this data file, excluding the header line? Each `hadm_id` identifies a hospitalization. How many hospitalizations are in this data file? How many unique patients (identified by `subject_id`) are in this data file? Do they match the number of patients listed in the `patients.csv.gz` file? (Hint: combine Linux commands `zcat <`, `head`/`tail`, `awk`, `sort`, `uniq`, `wc`, and so on.)

```{bash}
# display first 5 lines
zcat < ~/mimic/hosp/admissions.csv.gz | head -5
```
**Solution:** This script uncompresses the file and displays the first 5 lines of the admissions file.
```{bash}
# how many rows excluding header line
zcat < ~/mimic/hosp/admissions.csv.gz | tail -n +2 | wc -l
```
**Solution:** This script counts the number of lines, aside of the header, in the admissions file. There are 546,028 lines in the admissions file, excluding the header.
```{bash}
# hospitalizations
zcat < ~/mimic/hosp/admissions.csv.gz | tail -n +2 | awk -F, '{print $2}' | sort | uniq | wc -l
```
**Solution:** This script finds the list of unique hospitalizations and counts how many there are. There are 546,028 hospitalizations in the admissions file, the same as the number of rows, which means all hospitalizations are unique.
```{bash}
#patients
zcat < ~/mimic/hosp/admissions.csv.gz | tail -n +2 | awk -F, '{print $1}' | sort | uniq | wc -l
```
**Solution:** This script finds the list of unique patients and counts how many there are. There are 223,452 unique patients in the admissions file.
```{bash}
#patients in patients.csv.gz
zcat < ~/mimic/hosp/patients.csv.gz | tail -n +2 | awk -F, '{print $1}' | sort | uniq | wc -l
```
**Solution:** This script finds the list of unique patients in the patients file and counts how many there are. There are 364,627 unique patients in the patients file. The number of unique patients in the admissions file (223,452) does not match the number of unique patients in the patients file (364,627).

6. What are the possible values taken by each of the variable `admission_type`, `admission_location`, `insurance`, and `ethnicity`? Also report the count for each unique value of these variables in decreasing order. (Hint: combine Linux commands `zcat`, `head`/`tail`, `awk`, `uniq -c`, `wc`, `sort`, and so on; skip the header line.)

```{bash}
# admission_type => 6
zcat < ~/mimic/hosp/admissions.csv.gz | tail -n +2 | awk -F, '{print $6}'| sort | uniq -c | sort -nr
```t $5}' | sort | uniq -c | sort -nr

```{bash}
# admission_location, 8
zcat < ~/mimic/hosp/admissions.csv.gz | tail -n +2 | awk -F, '{print $8}' | sort | uniq -c | sort -nr
```

```{bash}
# insurance, 11
zcat < ~/mimic/hosp/admissions.csv.gz | tail -n +2 | awk -F, '{print $10}' | sort | uniq -c | sort -nr
```

```{bash}
# ethnicity, 14
zcat < ~/mimic/hosp/admissions.csv.gz | tail -n +2 | awk -F, '{print $13}' | sort | uniq -c | sort -nr
```
**Solution:** Each script searches the admissions file, excluding header, for the unique values of the specific column and counts how many times they show up. 

7. The `icusays.csv.gz` file contains all the ICU stays during the study period. How many ICU stays, identified by `stay_id`, are in this data file? How many unique patients, identified by `subject_id`, are in this data file?

```{bash}
zcat < ~/mimic/icu/icustays.csv.gz | tail -n +2 | awk -F, '{print $3}' | sort | uniq | wc -l

zcat < ~/mimic/icu/icustays.csv.gz | wc -l

zcat < ~/mimic/icu/icustays.csv.gz | tail -n +2 | awk -F, '{print $1}' | sort | uniq | wc -l
```
**Solution:** The number of ICU stays in the file is 94,458, which is also the same number of rows in the file, excluding the header. There are 65,366 unique patients in the data file.

8. _To compress, or not to compress. That's the question._ Let's focus on the big data file `labevents.csv.gz`. Compare compressed gz file size to the uncompressed file size. Compare the run times of `zcat < ~/mimic/labevents.csv.gz | wc -l` versus `wc -l labevents.csv`. Discuss the trade off between storage and speed for big data files. (Hint: `gzip -dk < FILENAME.gz > ./FILENAME`. Remember to delete the large `labevents.csv` file after the exercise.)

```{bash}
gzip -dk < ~/mimic/hosp/labevents.csv.gz > ~/mimic/labevents.csv
```

```{bash}
time zcat < ~/mimic/hosp/labevents.csv.gz | wc -l
time wc -l ~/mimic/labevents.csv
```

```{bash}
ls -l ~/mimic/hosp/labevents.csv.gz
ls -l ~/mimic/labevents.csv
```

**Solution:** The compressed file, labevents.csv.gz, is around 2.6 GB while the decompressed file, labevents.csv, is around 18 GB. Comparing the real times, the difference between the two commands is only 5 seconds, since the compressed file takes 40sec and the decompressed file takes 35sec. With the storage cost of 18GB compared to 2GB and very similar run times, it is better to just store the file as compressed and use zcat to access its contents.

```{bash}
rm ~/mimic/labevents.csv
```

## Q4. Who's popular in Pride and Prejudice

1. You and your friend just have finished reading *Pride and Prejudice* by Jane Austen. Among the four main characters in the book, Elizabeth, Jane, Lydia, and Darcy, your friend thinks that Darcy was the most mentioned. You, however, are certain it was Elizabeth. Obtain the full text of the novel from <http://www.gutenberg.org/cache/epub/42671/pg42671.txt> and save to your local folder. 
```{bash}
#| eval: false
wget -nc http://www.gutenberg.org/cache/epub/42671/pg42671.txt
```
Explain what `wget -nc` does. Do **not** put this text file `pg42671.txt` in Git. Complete the following loop to tabulate the number of times each of the four characters is mentioned using Linux commands.
```{bash}
#| eval: false
wget -nc http://www.gutenberg.org/cache/epub/42671/pg42671.txt
for char in Elizabeth Jane Lydia Darcy
do
  echo $char:
  # some bash commands here
done
```

2. What's the difference between the following two commands?
```{bash}
#| eval: false
echo 'hello, world' > test1.txt
```
and
```{bash}
#| eval: false
echo 'hello, world' >> test2.txt
```

3. Using your favorite text editor (e.g., `vi`), type the following and save the file as `middle.sh`:
```{bash eval=FALSE}
#!/bin/sh
# Select lines from the middle of a file.
# Usage: bash middle.sh filename end_line num_lines
head -n "$2" "$1" | tail -n "$3"
```
Using `chmod` to make the file executable by the owner, and run
```{bash}
#| eval: false
./middle.sh pg42671.txt 20 5
```
Explain the output. Explain the meaning of `"$1"`, `"$2"`, and `"$3"` in this shell script. Why do we need the first line of the shell script?

## Q5. More fun with Linux

Try following commands in Bash and interpret the results: `cal`, `cal 2026`, `cal 9 1752` (anything unusual?), `date`, `hostname`, `arch`, `uname -a`, `uptime`, `who am i`, `who`, `w`, `id`, `last | head`, `echo {con,pre}{sent,fer}{s,ed}`, `time sleep 5`, `history | tail`.

## Q6. Book

1. Git clone the repository <https://github.com/christophergandrud/Rep-Res-Book> for the book _Reproducible Research with R and RStudio_ to your local machine. Do **not** put this repository within your homework repository `biostat-203b-2026-winter`.

2. Open the project by clicking `rep-res-3rd-edition.Rproj` and compile the book by clicking `Build Book` in the `Build` panel of RStudio. (Hint: I was able to build `git_book` and `epub_book` directly. For `pdf_book`, I needed to add a line `\usepackage{hyperref}` to the file `Rep-Res-Book/rep-res-3rd-edition/latex/preabmle.tex`.)

The point of this exercise is (1) to obtain the book for free and (2) to see an example how a complicated project such as a book can be organized in a reproducible way. Use `sudo apt install PKGNAME` to install required Ubuntu packages and `tlmgr install PKGNAME` to install missing TexLive packages.

For grading purpose, include a screenshot of Section 4.1.5 of the book here.

## Q7. AI assistant

Which AI assistants (e.g., GitHub Copilot) do you use when working on this assignment? Which AI model (e.g., GPT-5 mini, GPT-5, Claude Sonnet 4.5) does the AI assistant use? How do you use them? Do you think they help improve your productivity? 

Give 5 instances where AI model gave incorrect or misleading answers. You can use screenshots or copy-paste the Q&A.
