---
title: "cohort"
format: html
---

```{r}
library(bigrquery)
library(dbplyr)
library(DBI)
library(gt)
library(gtsummary)
library(tidyverse)
library(forcats)
```

```{r}
# path to the service account token 
satoken <- "biostat-203b-2026-winter-92fefbfab477.json"
# BigQuery authentication using service account
bq_auth(path = "~/BIOSTAT203B/203b-hw/hw4/biostat-203b-2026-winter-92fefbfab477.json")
```
Connect to BigQuery database `mimiciv_3_1` in GCP (Google Cloud Platform), using the project billing account `biostat-203b-2025-winter`.
```{r}
# connect to the BigQuery database `biostat-203b-2025-mimiciv_3_1`
con_bq <- dbConnect(
    bigrquery::bigquery(),
    project = "biostat-203b-2025-winter",
    dataset = "mimiciv_3_1",
    billing = "biostat-203b-2025-winter"
)
con_bq
```

Building the cohort: Joining transfers and icustays together
```{r}
# find all units listed under icustays
icu_careunits <- tbl(con_bq, "icustays") %>%
  distinct(first_careunit) %>%
  pull(first_careunit)
```

```{r}
# all transfers of patients who go from ed to icu per visit
ed_to_icu <- tbl(con_bq, "transfers") %>% #start with transfers
  mutate(
    is_ed = careunit == "Emergency Department",
    is_icu = careunit %in% icu_careunits
  ) %>%
  group_by(subject_id, hadm_id) %>%
  window_order(intime) %>%
  mutate( 
    is_last_ed = is_ed & !sql("LEAD(is_ed, 1, FALSE) OVER (
                      PARTITION BY subject_id, hadm_id
                      ORDER BY intime
                     )"),
    next_is_icu = sql("LEAD(is_icu, 1, FALSE) OVER (
                      PARTITION BY subject_id, hadm_id
                      ORDER BY intime     
                     )")
  ) %>%
  mutate(
    any_next_icu = sql("MAX(next_is_icu) OVER (
                      PARTITION BY subject_id, hadm_id
                      ORDER BY intime
                      ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING
                     )") 
  ) %>%
  ungroup() %>%
  filter(is_ed) %>%
  group_by(subject_id, hadm_id) %>%
  mutate( #can't use slice_min so we use row_number to get the first ed transfer per visit
    stay_num = sql("ROW_NUMBER() OVER (
                      PARTITION BY subject_id, hadm_id
                      ORDER BY intime
                     )")
  ) %>%
  filter(stay_num == 1) %>%
  ungroup() %>%
  left_join(
    tbl(con_bq, "icustays") %>%
      arrange(subject_id, hadm_id, intime) %>%
      group_by(subject_id, hadm_id) %>%
      filter(intime == min(intime)) %>%
      ungroup() %>%
      rename(intime_icu = intime, outtime_icu = outtime),
    by = c("subject_id", "hadm_id")
  ) %>%  # join in BQ
  select(-eventtype, -stay_num, -is_icu, 
         -last_careunit, -los, -transfer_id) %>%
  collect()

```
```{r}
ed_to_icu <- ed_to_icu %>%
  mutate(
    icu_within_3hrs = if_else(
      !is.na(intime_icu) & !is.na(intime) &
      intime_icu >= intime &
      intime_icu <= intime + hours(3),
      1L, 0L),
  ed_to_icu_minutes = if_else(
      !is.na(intime_icu) & !is.na(intime),
      as.numeric(difftime(intime_icu, intime, units = "mins")),
      NA_real_
    )
  )
ed_to_icu

```

```{r}
# # in ed_to_icu, but not ed_icu_basecase - 0
# anti_join(ed_to_icu, ed_to_icu_basecase, by = "hadm_id")
# 
# #in ed_to_icu_basecase but not ed_to_icu -
# anti_join(ed_to_icu_basecase, ed_to_icu, by = "hadm_id")
# 
# # in both
# semi_join(ed_to_icu, ed_to_icu_basecase, by = "hadm_id")
# 
# ed_to_icu %>%
#   group_by(hadm_id) %>%
#   summarize(n = n()) %>%
#   filter(n > 1)

sum(ed_to_icu$icu_within_3hrs == 1)
sum(!is.na(ed_to_icu$intime_icu))
```

Finding all trauma patients through ICD codes
```{r}
all_trauma_patients <- tbl(con_bq, "diagnoses_icd") %>%
    filter(
      # ICD-10 Logic: Must be version 10 AND within the S00-T88 range
      (icd_version == 10 & icd_code >= "S00" & icd_code <= "T88") | 
        
        # ICD-9 Logic: Must be version 9 AND (Numeric range OR E-code range)
        (icd_version == 9 & (
          (icd_code >= "800" & icd_code <= "959") | 
            (icd_code >= "E800" & icd_code <= "E999")
        ))
  ) %>%
  left_join(
    tbl(con_bq, "d_icd_diagnoses"),
    by = c("icd_code", "icd_version")
  ) %>%
  collect()
```

```{r}
ed_to_icu_trauma <- ed_to_icu %>%
  semi_join(
    all_trauma_patients,
    by = c("subject_id", "hadm_id")
  )

# number of stays that transferred within 3 hours
sum(ed_to_icu_icd_trauma_only$icu_within_3hrs == 1)
# number of stays that did not go to the icu
sum(!is.na(ed_to_icu_icd_trauma_only$intime_icu))
```

Now that we have all the patients and their stays, add in labs, vitals, and demographic data
```{r}
demographics <- tbl(con_bq, "patients") %>%
  select(subject_id, gender, anchor_age, anchor_year) %>%
  inner_join(
    tbl(con_bq, "admissions") %>%
      select(subject_id, hadm_id, insurance, 
             race, marital_status, admission_type),
    by = "subject_id") %>%
  collect()

ed_to_icu_trauma_demo <- ed_to_icu_trauma %>%
  inner_join(
    demographics,
    by = c("subject_id", "hadm_id")
  )
  
```














